PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX sdtm: <https://w3id.org/c-path/biolink_sdtm_owl/>




# Query for the demographics data (sex only), for both models, like Table 3 in the paper.
SELECT * WHERE
{
	?s a biolink:Case .
	?s ?p ?o .
	?o a biolink:BiologicalSex .
	?o biolink:has_qualitative_value ?o2
}

