PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX sdtm: <https://w3id.org/c-path/biolink_sdtm_owl/>



# Query for the demographics data (sex only) and lab tests, for both models, like Table 3 in the paper.
select * where { 
    ?pat a biolink:Case . 
    ?pat ?p1 ?o . 
    ?o a biolink:BiologicalSex . 
    ?pat ?p2 ?o2 .
    ?o2 a biolink:MaterialSample .
    ?o2 ?p3 ?o3 .
    ?o3 a biolink:Procedure .
    ?o3 ?p4 ?o4 .
    ?o4 a biolink:InformationContentEntity .
} 

